version: "3.7"

services:
  gunicorn:
    volumes:
      - ./src/static:/static
    env_file:
      - .env
    build: 
      context: .
    ports:
      - "5002:5001"
  nginx:
    build: ./nginx
    volumes:
      - ./src/static:/static
      - phpmyadmin:/phpmyadmin/:ro # named volume 'phpmyadmin' from phpmyadmin service
    ports:
      - "80:80"
    depends_on:
      - gunicorn
      - phpmyadmin
  phpmyadmin:
    image: phpmyadmin:fpm
    restart: always
    volumes:
      - phpmyadmin:/var/www/html/
    environment:
      - PMA_HOST=${MYSQLHOST}
      - PMA_PORT=${MYSQLPORT}

volumes:
  static:
  phpmyadmin:
